//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoService.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICE_SENSOR_DETAIL
    {
        public string DEVICE_ID { get; set; }
        public string VALUE { get; set; }
        public Nullable<System.DateTime> TIME_UPDATE { get; set; }
        public Nullable<int> IS_MEDIUM { get; set; }
    }
}
