//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoService.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class GARDEN
    {
        public string GARDEN_ID { get; set; }
        public string GARDEN_NAME { get; set; }
        public string USER_ID { get; set; }
        public Nullable<int> ACTIVE { get; set; }
        public string TOKEN_KEY { get; set; }
        public string IMAGE { get; set; }
    }
}
