//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoService.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ioTSystemEntities : DbContext
    {
        public ioTSystemEntities()
            : base("name=ioTSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEVICE> DEVICEs { get; set; }
        public virtual DbSet<DEVICE_CATEGORY> DEVICE_CATEGORY { get; set; }
        public virtual DbSet<DEVICE_CONTROL_DETAIL> DEVICE_CONTROL_DETAIL { get; set; }
        public virtual DbSet<DEVICE_SENSOR_DETAIL> DEVICE_SENSOR_DETAIL { get; set; }
        public virtual DbSet<GARDEN> GARDENs { get; set; }
        public virtual DbSet<PERMISSION> PERMISSIONs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
